travis:
  secure:
    BINSTAR_TOKEN: uUe0hBkQLM04Dkch0Zoe4UvAsds0xvpA4GB96lDWKdZNjPHCPiGpg+Zf1LQ7tN/g40bZz+G21nyCh5EHebqiuL8v/KHyjntblnyipcKPkr9hQ5+FsbStuiGFujJRYa3lA0rCcJTck/xAHSKzYQvY0HA73I6lWxRFGbiho6sHo1+QkIHjlToCJfxydAbpdQe8Uz4zhn15xNaZaHZD/qxkbzTFOyk2N7aafhh6LBrMPc5bW2+qQ0HJNWizstDuFSKNfV45rsaOuYPxrOQf9+yxp8JkTXEtAARXP2CpGM+tgcasRa8XbO3iy12jIkHmtFeZFEkX15JUTrh3Ve7t0kARMpk76OSm3yg0oTRW8T5UA68doDUtPkOxumW7wqVF0heRspTjVlaC/RVfsvUmzxUBZ9ehvIOsqYT0dZo0gxzJDZIoKvs2p9qYwjVv0AWlKOxgptMj3GDHUNjUJN0MrCkZ1rGbH0Qe+1Qfgfdc7SPFxm3vLeZipjH18htPhsebAxbKxkxvN8sqLfDyH8BILwWDhdPXJbu7bCoIXJDcwDEiwDnMFj5BZIIuJYJegwaUfNdpDxgZmtPyWaC/NFqXHLUu8IHu7xXLSE414Ew1ZfHMO6wIiFKgtm5MhayXTpg99fjl4x+za35l1UtG6oG4WZGhk3Q33ZRkRvecrkTbX1/bDBA=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
